# Increase single-line thresholds compared to `use_small_heuristics = "Default"`:
fn_call_width = 80
attr_fn_like_width = 80
struct_lit_width = 40
struct_variant_width = 40
array_width = 60
chain_width = 80
single_line_if_else_max_width = 60
